Resources:
  # create a security group
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Enable http(80) & ssh(22) access
      GroupName: WebServer-SG
      VpcId: vpc-010d68eacd137a9bd
      SecurityGroupIngress:
        # allow http
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 # any IP
        # allow ssh  
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 24.15.193.255/32 # only for demo else use your IP or corporate gateway IP
      Tags: 
       - Key: Name
         Value: Kitten-SG


  # EC2 instance which will have access for http and ssh
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SubnetId: subnet-0f35abad90d194262
      SecurityGroupIds:
        - !Ref MySecurityGroup
      KeyName: firstKey
      ImageId: ami-0b5eea76982371e91
      Tags: 
       - Key: Name
         Value: My Kitten Web Server
      UserData: 
        Fn::Base64: 
          !Sub |
            #!/bin/bash -xe
            sudo su
            yum update -y # good practice to update existing packages
            yum install -y httpd # install web server 
            systemctl start httpd
            systemctl enable httpd
          